version: '3.8'

services:
  exchangerate-api:
    build:
      context: .
      dockerfile: ExchangeRateApi/Dockerfile
    container_name: exchangerate-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - Logging__LogLevel__Default=Information
      - Logging__LogLevel__Microsoft.AspNetCore=Warning
    networks:
      - exchangerate-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/swagger"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  exchangerate-network:
    driver: bridge