version: '3.8'

services:
  exchangerate-api:
    build:
      context: .
      dockerfile: ExchangeRateApi/Dockerfile
    container_name: exchangerate-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      Logging__LogLevel__Default: Information
      Logging__LogLevel__Microsoft.AspNetCore: Warning
    ports:
      - "18080:8080"     # hit http://<server-ip>:18080
    networks:
      - kvblog_backend
    restart: unless-stopped

networks:
  kvblog_backend:
    external: true